version: '3'

services:
  backend:
    container_name: backend_tests
    environment:
      - DB_HOST_TEST=db_test

    networks:
      - backend_tests_network
    build:
      context: .
      dockerfile: Dockerfile_tests
    ports:
      - "8000:8000"
    depends_on:
      - db_test

  db_test:
    image: postgres:15.1-alpine
    container_name: db_test
    environment:
      - POSTGRES_HOST=${DB_HOST_TEST}
      - POSTGRES_DB=${DB_NAME_TEST}
      - POSTGRES_USER=${DB_USER_TEST}
      - POSTGRES_PASSWORD=${DB_PASS_TEST}
    networks:
      - backend_tests_network
    
    command: -p ${DB_PORT_TEST}
    expose:
      - ${DB_PORT_TEST}
    ports:
      - ${DB_PORT_TEST}:${DB_PORT_TEST}
    healthcheck:
      test: [ "CMD-SHELL", 'pg_isready', '-U', 'postgres', '-d', 'test_menu' ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s


networks:
  backend_tests_network:
    name: backend_tests_network
