version: '3'

services:
  backend:
    container_name: backend
    environment:
      - DB_HOST=db

    networks:
      - backend_network
    build:
      context: .
      dockerfile: Dockerfile_main
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:15.1-alpine
    environment:
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    networks:
      - backend_network
    container_name: db
    command: -p ${DB_PORT}
    expose:
      - ${DB_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}
    healthcheck:
      test: [ "CMD-SHELL", 'pg_isready', '-U', 'postgres', '-d', 'test_menu' ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s


networks:
  backend_network:
    name: backend_network
volumes:
  pgdata:
