FROM python:3.10-slim

ENV PYTHONUNBUFFERED=1

RUN mkdir /backend
WORKDIR /backend
COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

ENTRYPOINT cd src && celery -A celery_app.celery_config worker --loglevel=info
