version: '3'

services:
  backend:
    container_name: backend
    networks:
      - backend_network
    build:
      context: .
      dockerfile: Dockerfile_main
    ports:
      - "8000:8000"
    restart: always
    external_links:
      - db-pg:db-pg
      - redis_app:redis_app
    environment:
      - DB_HOST=db-pg
      - REDIS_HOST=redis_app
    depends_on:
        db:
          condition: service_healthy
        redis:
          condition: service_healthy
        rabbitmq:
          condition: service_healthy

  db:
    image: postgres:15.1-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    networks:
      - backend_network
    container_name: db-pg
    command: -p ${DB_PORT}
    expose:
      - ${DB_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data

    healthcheck:
      test: pg_isready -U ${DB_USER} -p ${DB_PORT}
      interval: 5s
      timeout: 3s
      retries: 3

  redis:
    image: redis:7.2-alpine
    container_name: redis_app
    command: --port ${REDIS_PORT}
    networks:
      - backend_network
    expose:
      - ${REDIS_PORT}
    healthcheck:
      test: redis-cli -p ${REDIS_PORT} ping
      interval: 5s
      timeout: 3s
      retries: 2

  rabbitmq:
    image: rabbitmq:3.12.12-alpine
    container_name: rabbitmq_app
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PORT: ${RABBITMQ_PORT}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_HOST}
    ports:
      - ${RABBITMQ_PORT}:${RABBITMQ_PORT}
    networks:
      - backend_network
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 3s
      retries: 2

  celery:
    container_name: celery_app
    build:
      context: .
      dockerfile: Dockerfile_main_celery
    external_links:
      - rabbitmq_app:rabbitmq_app
    environment:
      - RABBITMQ_HOST=rabbitmq_app
    networks:
      - backend_network
    depends_on:
      - backend
      - rabbitmq

networks:
  backend_network:
    name: backend_network
volumes:
  pgdata:
