version: '3'

services:
  backend:
    container_name: backend_tests
    external_links:
      - db-test-pg:db-test-pg
      - test_redis_app:test_redis_app
    environment:
      - DB_HOST_TEST=db-test-pg
      - REDIS_HOST=test_redis_app
    networks:
      - backend_tests_network
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile_tests
    ports:
      - "8000:8000"
    depends_on:
        db_test:
          condition: service_healthy
        test_redis:
          condition: service_healthy

  db_test:
    image: postgres:15.1-alpine
    container_name: db-test-pg
    environment:
      - POSTGRES_DB=${DB_NAME_TEST}
      - POSTGRES_USER=${DB_USER_TEST}
      - POSTGRES_PASSWORD=${DB_PASS_TEST}
    networks:
      - backend_tests_network
    command: -p ${DB_PORT_TEST}
    expose:
      - ${DB_PORT_TEST}

    healthcheck:
      test: pg_isready -U ${DB_USER_TEST} -p ${DB_PORT_TEST}
      interval: 5s
      timeout: 3s
      retries: 3

  test_redis:
    image: redis:7.2-alpine
    container_name: test_redis_app
    command: --port ${REDIS_PORT}
    networks:
      - backend_tests_network
    expose:
      - ${REDIS_PORT}
    healthcheck:
      test: redis-cli -p ${REDIS_PORT} ping
      interval: 5s
      timeout: 3s
      retries: 2

networks:
  backend_tests_network:
    name: backend_tests_network
